# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Matt Newman
tagline:             ''
description:         'Personal website & blog for a developer living in Brisbane, Australia.'
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Matt Newman
  url:               http://mdjnewman.me

exclude: [".editorconfig", ".gitignore", "CNAME", "Gemfile", "Gemfile.lock", "README.md"]
include: [".well-known"]

gems:
  - jekyll-sitemap

