# Dependencies
markdown:            kramdown

# Permalinks
permalink:           /:year/:month/:title/

# Setup
title:               Matt Newman
tagline:             ''
description:         'Personal website & blog for a developer currently living in Chicago (previously Brisbane, Australia).'
paginate:            5

# About/contact
author:
  name:              Matt Newman
  url:               https://mdjnewman.me

exclude: [".editorconfig", ".gitignore", "CNAME", "Gemfile", "Gemfile.lock", "README.md"]
include: [".well-known"]

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
